### ISSUE TITLE
Using /m <map name> currently DC's you

### ISSUE THREAD

**Issue by Silwhoon** [doriyan13/SpringStory#19]
Here is the error I am receiving:
`<nioEventLoopGroup-6-1> [StageHandler]: Got an invalid portal name while trying to transfer between maps - `

This command is only available to GM's

**Comment by doriyan13** [comment]
Oh try using !goto <mapName> or !warp <mapID>

**Comment by Silwhoon** [comment]
Yep I have been, just figured I'd bring this up as its a pretty useful command that I like to use

**Comment by doriyan13** [comment]
👍🏼

**Comment by doriyan13** [comment]
it's /m <mapID>, fixed 👍🏼
