### ISSUE TITLE
Skills that affect the players maxHP/maxMP (Hyper Body) do not change the players current HP/MP when it expires

### ISSUE THREAD

**Issue by Silwhoon** [doriyan13/SpringStory#33]
If you use Hyper Body and fully heal yourself, when the skill timer runs out, your Max HP & Max MP are returned to their original value, but your current HP/MP is still at its previous max

See image of HP and MP:
![image](https://github.com/doriyan13/SpringStory/assets/29519598/cdb9321d-f118-45c6-8756-88153902952b)

**Comment by doriyan13** [comment]
Oh that's a rough one lmao, I will fix it 👍
